# Google Cloud Platform Deployment Configuration

# Cloud Run Service for Node.js API
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crop-predictor-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/PROJECT_ID/crop-predictor-api
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: openweather-secret
              key: api-key
        - name: GOOGLE_CLOUD_PROJECT_ID
          value: "PROJECT_ID"
        - name: VERTEX_AI_LOCATION
          value: "us-central1"
        - name: VERTEX_AI_ENDPOINT_ID
          value: "YOUR_ENDPOINT_ID"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

---
# Cloud Run Service for Flask ML API
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crop-predictor-ml
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/crop-predictor-ml
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
